env:
  global:
    - CC_TEST_REPORTER_ID=ade332bf1e581a7141bc400f5efc37c686f7a652990d71d1d3666afce03a5b86


language: php

php:
  - 7.2

# faster builds on new travis setup not using sudo
sudo: required
dist: xenial

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.composer/vendor
    - vendor

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client


before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - php yii migrate --interactive=0 -c

script:
  - ./tests/bin/yii fixture/load '*' --interactive=0
  - ./vendor/bin/codecept run unit --coverage --coverage-xml

after_script:
  - mv tests/_output/coverage.xml clover.xml
  - ./cc-test-reporter after-build -d --coverage-input-type clover --id 12345 --exit-code $TRAVIS_TEST_RESULT


